### ISSUE TITLE
unable to flash

### ISSUE THREAD

**Issue by astramage** [embeddedkink/lockbox-firmware#2]
unable to flash through the installer and I just get an HTTP 500 error after a manual flash

**Comment by embeddedkink** [comment]
Hi! This is not enough information to triage a potential issue with. Can you please provide the following
- Browser and version
- What board or chip you tried to flash (be specific)
- Did you follow the precise instructions for flashing, including not connecting through a hub and holding the flash button while connecting?
- What did you mean with manual flashing? If you meant using PlatformIO or Arduino IDE, did you not forget to upload the filesystem?

**Comment by astramage** [comment]
browser: chrome Version 114.0.5735.134
board: https://www.amazon.ca/dp/B0B49SZNKP?psc=1&ref=ppx_yo2ov_dt_b_product_details and https://www.amazon.ca/dp/B07PR9T5R5?psc=1&ref=ppx_yo2ov_dt_b_product_details
I followed all the instructions
I used platformIO and I'm not sure what you mean about the filesystem

**Comment by embeddedkink** [comment]
The code of the box consists of two parts. The compiled code that is uploaded when you hit "Upload" and the filesystem that has to be uploaded separately. Look for "upload file system image" in PlatformIO. This uploads the files in the "data" folder.
It is unclear to me why the web flasher did not work for you. Feel free to reopen the issue if you have more information

**Comment by astramage** [comment]
i am unable to find  "upload file system image" i tried some more with the web flasher and i just get this 
![image](https://github.com/embeddedkink/lockbox-firmware/assets/133549141/7c313a8a-20c6-447f-a190-6f1f0bd1ea95)
